### ISSUE TITLE
Question: Why use a 64 keylen to scrypt but then only use 32 bytes?

### ISSUE THREAD

**Issue by domosapien** [chrisveness/scrypt-kdf#12]
Sorry for imposing my lack of crypto knowledge on you, but I don't see the benefit of having scrypt generate more bytes to then only use some of them. Wouldn't passing 32 as the keylen give you the same effective result?

**Comment by chrisveness** [comment]
Good question – I also don't know why it is done that way, I simply followed Percival's method: see
- https://github.com/Tarsnap/scrypt/blob/master/FORMAT
- https://github.com/Tarsnap/scrypt/blob/master/lib/scryptenc/scryptenc.c#L233

Can any crypto experts shed some light?

**Comment by chrisveness** [comment]
Further details – my lines [scrypt.js:100/104](https://github.com/chrisveness/scrypt-kdf/blob/2d9a9b7adf4c94acfa09d86719c844b3c3a207ab/scrypt.js#L100-L104):

    const hmacKey = await cryptoScrypt(passphrase, struct.salt, 64, params);
    ...
    const hmacHash = crypto.createHmac('sha256', hmacKey.slice(32)).update(prefix64).digest();

correspond to Percival's lines, from [scryptenc.c:214-252](https://github.com/Tarsnap/scrypt/blob/7647c6d6f09b0cb61a46d191b1af361aa2bd8e99/lib/scryptenc/scryptenc.c#L214-L252):

    uint8_t * key_hmac = &dk[32];
    ...
    crypto_scrypt(passwd, passwdlen, salt, 32, N, r, p, dk, 64);
    ...
    HMAC_SHA256_Init(&hctx, key_hmac, 32);
    HMAC_SHA256_Update(&hctx, header, 64);
    HMAC_SHA256_Final(hbuf, &hctx);

(Percival's `dk` being the equivalent of my `hmacKey`).

My C is not so fluent, am I correct that `&dk[32]` accesses the second 32 bytes from `dk`?

**Comment by domosapien** [comment]
Yes, that is pointing to the 32nd element in the array, so it would use the latter half of the array for the init.

**Comment by domosapien** [comment]
It appears that the function [scryptenc_buf](https://github.com/Tarsnap/scrypt/blob/7647c6d6f09b0cb61a46d191b1af361aa2bd8e99/lib/scryptenc/scryptenc.c#L325) uses the first 32 bytes. The array gets initialized in the setup function and the last 32 bytes are used there, but the whole array is then used outside of it.

**Comment by chrisveness** [comment]
So I take it the conclusion is that the scrypt-kdf implementation does have to use a key length of 64 for the derived key, even though it only uses the second 32 bytes of it, for compatibility with the Tarsnap scrypt (which uses the first 32 bytes in the file encryption).

Thanks for helping clarify that.
