### ISSUE TITLE
`pickParams` does not return accurate result on first few invocations

### ISSUE THREAD

**Issue by simonratner** [chrisveness/scrypt-kdf#18]
```
> let scrypt = require('scrypt-kdf')
undefined
> scrypt.pickParams(0.1)
512 0.002940500020980835 174120.04636858223
{ logN: 10, r: 8, p: 1 }
> scrypt.pickParams(0.1)
3072 0.0010730000734329225 2863000.7360312105
{ logN: 13, r: 8, p: 1 }
> scrypt.pickParams(0.1)
4096 0.0010850999355316161 3774767.526820719
{ logN: 13, r: 8, p: 1 }
```

This patterns is very reproducible, at least with node 12.18.3. I suspect this might be JIT in action, since the code is in javascript, or some similar effect. As you can see from the debug output, on first execution it only does a single iteration of the timing loop, returning an under-estimate of the real performance.

Suggest increasing the timing loop from just 1ms to several milliseconds. 

Here are the results using 10ms timing loop:
```
> let scrypt = require('scrypt-kdf')
undefined
> scrypt.pickParams(0.1)
24064 0.010037699937820435 2397361.9603163
{ logN: 12, r: 8, p: 1 }
> scrypt.pickParams(0.1)
37376 0.010131500005722046 3689088.484320275
{ logN: 13, r: 8, p: 1 }
> scrypt.pickParams(0.1)
36864 0.010046800017356873 3669228.0065606637
{ logN: 13, r: 8, p: 1 }
> scrypt.pickParams(0.1)
70144 0.010081699967384339 6957556.783769137
{ logN: 14, r: 8, p: 1 }
```

And here are the results using 100ms timing loop:
```
> let scrypt = require('scrypt-kdf')
undefined
> scrypt.pickParams(0.1)
790016 0.10005019998550416 7896196.110697051
{ logN: 14, r: 8, p: 1 }
> scrypt.pickParams(0.1)
1000448 0.10005380010604858 9999100.473341437
{ logN: 14, r: 8, p: 1 }
```

Since this function isn't expected to be called frequently, I think making it slower but more accurate by increasing the number of iterations of the timing loop is warranted. At least, it could be a parameter that caller can specify, if they are willing to wait (for example, the function is only called once on server startup, where 100ms might be perfectly acceptable).

**Comment by simonratner** [comment]
I have performed the same test without the REPL overhead, and 10ms loop produces quite consistent results:
```
$ node -p "require('scrypt-kdf').pickParams(0.1)"
{ logN: 14, r: 8, p: 1 }

$ node -p "require('scrypt-kdf').pickParams(0.1)"
{ logN: 14, r: 8, p: 1 }

$ node -p "require('scrypt-kdf').pickParams(0.1)"
{ logN: 14, r: 8, p: 1 }
```

In comparison to the current 1ms loop, which produces the same under-estimate every time:
```
$ node -p "require('scrypt-kdf').pickParams(0.1)"
{ logN: 10, r: 8, p: 1 }

$ node -p "require('scrypt-kdf').pickParams(0.1)"
{ logN: 10, r: 8, p: 1 }

$ node -p "require('scrypt-kdf').pickParams(0.1)"
{ logN: 10, r: 8, p: 1 }
```

**Comment by chrisveness** [comment]
Apologies for the unconscionably long delay in responding to this: delayed under covid, then forgotten after it.

I've not been able to reliably reproduce the 1ms / 10ms / 100ms loop results, but I agree there is no requirement for performance on this function, so have upped it to a 100ms timing loop. It seems reasonable to me that it might be used once or twice a decade to verify Filippo Valsorda's recommendation for logN=15!

In empirical tests, it still seems to be underestimating logN by around 2: I haven't determined why, but have added a note to that effect.
